configs:
- id: PTC
  config:
    template: windchill.json
    skip: false
  type:
    settings:
      schema: builtin:rum.web.enablement
      schemaVersion: 1.0.6
      scope:
        configId: PTC
        configType: application-web
        property: id
        type: reference