configs:
- id: PTC
  config:
    template: windchill.json
    skip: false
  type:
    settings:
      schema: builtin:rum.web.browser-exclusion
      schemaVersion: 1.0.1
      scope:
        configId: PTC
        configType: application-web
        property: id
        type: reference
