configs:
- id: PTC
  config:
    template: windchill.json
    skip: false
  type:
    settings:
      schema: builtin:rum.web.ipaddress-exclusion
      schemaVersion: 6.0.2
      scope:
        configId: PTC
        configType: application-web
        property: id
        type: reference
