configs:
- id: PTC
  config:
    template: windchill.json
    skip: false
  type:
    settings:
      schema: builtin:rum.web.key-performance-metric-load-actions
      schemaVersion: "1.1"
      scope:
        configId: PTC
        configType: application-web
        property: id
        type: reference